import { useMemo, useState } from "react";
import { motion } from "framer-motion";
import { Star } from "lucide-react";

const initialReviews = [
  { id: 1, publication: "Audiophile Quarterly", quote: "Obsidian has achieved the impossible. A wireless headphone that rivals wired studio monitors.", author: "James Sterling", rating: 5 },
  { id: 2, publication: "TechRadar Pro", quote: "The ANC is terrifyingly good. It doesn't just reduce noise; it deletes the outside world.", author: "Sarah Jenkins", rating: 5 },
  { id: 3, publication: "Sound & Vision", quote: "Machined aluminum, memory foam, and titanium drivers. The build quality justifies every penny.", author: "Marcus Chen", rating: 5 },
  { id: 4, publication: "Wired", quote: "Minimalist brutalism meets acoustic perfection. Obsidian is a statement piece that happens to sound incredible.", author: "Elena Rostova", rating: 5 },
];

function Stars({ rating, interactive = false, onSelect }) {
  return <div className="flex gap-1">{[1, 2, 3, 4, 5].map((star) => <button type="button" key={star} disabled={!interactive} onClick={() => onSelect?.(star)} aria-label={`${star} stars`}><Star className={`w-5 h-5 ${star <= rating ? "fill-white text-white" : "text-white/20"}`} /></button>)}</div>;
}

export default function Reviews() {
  const [reviews, setReviews] = useState(initialReviews);
  const [form, setForm] = useState({ name: "", rating: 5, quote: "" });
  const [submitted, setSubmitted] = useState(false);
  const distribution = useMemo(() => [5, 4, 3, 2, 1].map((rating) => ({ rating, count: reviews.filter((review) => review.rating === rating).length })), [reviews]);
  const average = (reviews.reduce((sum, review) => sum + review.rating, 0) / reviews.length).toFixed(1);
  const submitReview = (event) => { event.preventDefault(); if (!form.name.trim() || !form.quote.trim()) return; setReviews((current) => [{ id: Date.now(), publication: "Verified listener", quote: form.quote.trim(), author: form.name.trim(), rating: form.rating }, ...current]); setForm({ name: "", rating: 5, quote: "" }); setSubmitted(true); window.setTimeout(() => setSubmitted(false), 2500); };

  return <div className="bg-brand-black min-h-screen pt-28 pb-24 px-6 overflow-x-hidden w-full max-w-[100vw]"><div className="max-w-7xl mx-auto"><div className="text-center mb-16"><motion.p initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="text-brand-light/50 text-xs font-bold uppercase tracking-[0.3em] mb-3">Critical Consensus</motion.p><motion.h1 initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="text-4xl sm:text-5xl md:text-7xl font-black text-brand-white uppercase tracking-tighter break-words w-full px-4 md:px-0">Uncompromising <br /> Verdicts.</motion.h1></div>
    <div className="grid lg:grid-cols-[.8fr_1.2fr] gap-4 mb-8"><div className="bg-brand-dark rounded-2xl border border-white/5 p-8 md:p-10 flex flex-col justify-center"><p className="text-xs uppercase tracking-[0.2em] text-brand-light/50">Listener rating</p><div className="flex items-center gap-5 mt-4"><span className="text-6xl font-black">{average}</span><div><Stars rating={Math.round(Number(average))} /><p className="text-xs text-brand-light/40 mt-2">Based on {reviews.length} reviews</p></div></div><div className="space-y-3 mt-8">{distribution.map(({ rating, count }) => <div key={rating} className="flex items-center gap-3 text-xs font-mono"><span className="w-8 text-brand-light/50">{rating} ★</span><div className="h-2 bg-white/10 rounded-full flex-1 overflow-hidden"><motion.div initial={{ width: 0 }} animate={{ width: `${(count / reviews.length) * 100}%` }} className="h-full bg-white rounded-full" /></div><span className="w-5 text-right text-brand-light/40">{count}</span></div>)}</div></div><div className="relative min-h-[360px] rounded-2xl overflow-hidden group"><img src="https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&q=80&w=2000" alt="Audio studio mixing console" className="absolute inset-0 w-full h-full object-cover grayscale opacity-40 mix-blend-lighten transition-transform duration-1000 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-brand-black via-brand-black/40 to-transparent" /><div className="absolute bottom-0 left-0 p-8 md:p-12"><Stars rating={5} /><h2 className="text-2xl md:text-4xl font-bold leading-tight mt-4">“The new gold standard for high-fidelity wireless audio.”</h2><p className="text-brand-light uppercase tracking-widest text-xs font-bold mt-4">— The Verge</p></div></div></div>
    <div className="grid lg:grid-cols-[1.4fr_.6fr] gap-8 items-start"><motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="grid grid-cols-1 md:grid-cols-2 gap-4">{reviews.map((review) => <motion.div layout key={review.id} className="bg-brand-dark p-8 rounded-2xl border border-white/5 flex flex-col justify-between"><div><div className="flex justify-between items-center mb-6 gap-3"><span className="text-brand-light/50 text-xs uppercase tracking-widest font-bold">{review.publication}</span><Stars rating={review.rating} /></div><p className="text-lg text-brand-white font-light leading-relaxed mb-6">“{review.quote}”</p></div><p className="text-brand-light/50 text-xs uppercase tracking-wider font-mono">{review.author}</p></motion.div>)}</motion.div>
      <form onSubmit={submitReview} className="bg-brand-dark rounded-2xl border border-white/10 p-7 md:p-8 lg:sticky lg:top-28"><p className="text-xs font-mono uppercase tracking-[0.2em] text-brand-light/50">Your experience</p><h2 className="text-3xl font-black uppercase tracking-tighter mt-2 mb-7">Write a review.</h2><label className="block text-xs uppercase tracking-widest text-brand-light/50 mb-2">Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="mt-2 w-full bg-transparent border-b border-white/20 focus:border-white outline-none py-3 text-white" placeholder="Your name" /></label><div className="mt-6"><p className="text-xs uppercase tracking-widest text-brand-light/50 mb-3">Rating</p><Stars rating={form.rating} interactive onSelect={(rating) => setForm({ ...form, rating })} /></div><label className="block text-xs uppercase tracking-widest text-brand-light/50 mt-6">Review<textarea required value={form.quote} onChange={(e) => setForm({ ...form, quote: e.target.value })} rows="4" className="mt-2 w-full bg-transparent border border-white/20 focus:border-white outline-none p-3 text-white resize-none" placeholder="What do you hear?" /></label><button type="submit" className="mt-6 w-full py-4 bg-white text-black font-bold uppercase tracking-[0.15em] text-xs hover:bg-white/80 transition-colors">{submitted ? "Review published" : "Publish review"}</button></form>
    </div></div></div>;
}
